name = "WamIPE"
uuid = "41fd0477-1b5e-4379-aa5e-f7ca9a3197dc"
version = "0.1.0"
authors = ["Tarun <iTarun17@gmail.com>"]

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extensions]
WamIPEPlotsExt = "Plots"
WamIPEMakieExt = "CairoMakie"
WamIPELivePlotsExt = "Plots"
WamIPELiveMakieExt = "CairoMakie"
WamIPELiveTablesExt = ["CSV", "DataFrames"]

[compat]
AWS = "1.97.1"
AWSS3 = "0.11.4"
CSV = "0.10.15"
CairoMakie = "0.15.8"
CommonDataModel = "0.4.2"
DataFrames = "1.8.1"
DataInterpolations = "8.9.0"
Dates = "1.11.0"
EzXML = "1.2.3"
FilePathsBase = "0.9.24"
HTTP = "1.10.19"
Interpolations = "0.16.2"
NCDatasets = "0.14.10"
Plots = "1.41.4"
Printf = "1.11.0"
Serialization = "1.11.0"
Statistics = "1.11.1"
URIs = "1.6.1"

